version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: nuget	
  directory: "/Gatekeeper.SCIM.Client.Tests.Integration"
  schedule:	
    interval: daily	
  open-pull-requests-limit: 10	
- package-ecosystem: nuget	
  directory: "/Gatekeeper.SCIM.Client.Tests.Unit"
  schedule:	
    interval: daily	
  open-pull-requests-limit: 10
