name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Test Gatekeeper.SCIM.Client.Tests
      run: dotnet test Gatekeeper.SCIM.Client.Tests/ --collect:"XPlat Code Coverage" -r TestResults/
    - uses: codecov/codecov-action@v1
      with:
        directory: TestResults/
        fail_ci_if_error: true
        verbose: true
